- name: Create CSR using shell command
  shell: openssl req -nodes -newkey rsa:2048 -keyout 'birth.key' -out 'birth_cer.csr' -subj '/CN=device'
  delegate_to: 127.0.0.1

- name: Request a certificate from CAGW
  community.crypto.cagw_certificate:
    path: 'birth_cer.crt'
    csr: 'birth_cer.csr'
    cagw_api_client_cert_path: '/tmp/cagw_client_cert.pem'
    cagw_api_client_cert_key_path: '/tmp/cagw_client_key.pem'
    certificate_authority_id: '{{ ca_id }}'
    certificate_profile_id: '{{ profile_id }}'
    request_type: 'new'
    enrollment_format: 'X509'
    dn: 'cn=device'
    cagw_api_specification_path: '/tmp/cagw-api.yaml'
    connection_type: 'SM'
    remaining_days: '30'
    force: 'true'
  delegate_to: 127.0.0.1

- name: convert cert to DER encoding
  ansible.builtin.shell:
    cmd: openssl x509 -in birth_cer.crt -outform DER -out /tmp/birth.crt
  delegate_to: 127.0.0.1

- name: convert private key to DER encoding
  ansible.builtin.shell:
    cmd: openssl pkcs8 -topk8 -inform PEM -outform DER -in {{ working_path }}/files/key.pem -out /tmp/epa_private.p8 -nocrypt
  delegate_to: 127.0.0.1

- name: Create entrust user
  ansible.builtin.shell:
    cmd: useradd -ms /bin/bash entrust
  become: true

  #- name: Create entrust user
  #ansible.builtin.shell:
  #cmd: chmod -R 700 /opt/entrust
  #become: true

- name: create cert directory in /opt/entrust
  ansible.builtin.shell:
    cmd: mkdir -p /opt/entrust/cert/
  become: true

- name: create CA Certificates directory in /opt/entrust/cert/
  ansible.builtin.shell:
    cmd: mkdir -p /opt/entrust/cert/CACertificates
  become: true

- name: copy birth certificate to target
  copy:
    src: /tmp/sjas8.crt
    dest: /opt/entrust/cert/sjas8.crt
  become: true

- name: copy private key to target
  copy:
    src: /tmp/sjas8_private.p8
    dest: /opt/entrust/cert/sjas8_private.p8
  become: true

- name: copy CA certificate to target
  copy:
    src: /tmp/ca.crt
    dest: /opt/entrust/cert/CACertificates/ca.crt
  become: true

- name: copy IOT Agent tar file to target
  copy:
    src: /tmp/IoTAgent.x86_64-buildroot-linux-musl.tar
    dest: /tmp/IoTAgent.x86_64-buildroot-linux-musl.tar

- name: expand IoT Agent tar file on target machine
  ansible.builtin.shell:
    cmd: tar -xf IoTAgent.x86_64-buildroot-linux-musl.tar
    chdir: /tmp/

    #- name: create CA Certificates directory in /opt/entrust/cert/
    #ansible.builtin.shell:
    #cmd: mkdir -p /opt/entrust/IOT_AGENT
    #become: true

- name: copy IOT Agent to /opt/entrust
  ansible.builtin.shell:
    cmd: cp -r ./IOT_AGENT /opt/entrust/
    chdir: /tmp/
  become: true

- name: copy run IOT agent shell file to target machine
  copy:
    src: /tmp/runIoTAgent.sh
    dest: /opt/entrust/IOT_AGENT/runIoTAgent.sh
  become: true

- name: Create entrust user
  ansible.builtin.shell:
    cmd: sed -i 's/export container=false/export container=true/' /opt/entrust/I                                                                             OT_AGENT/Modules
  become: true

- name: Create entrust user
  ansible.builtin.shell:
    cmd: chmod 700 /opt/entrust/IOT_AGENT/runIoTAgent.sh
  become: true

- name: Create entrust user
  ansible.builtin.shell:
    cmd: chmod 700 /opt/entrust/IOT_AGENT/Resources/ntpEPA.sh
  become: true

- name: Create entrust user
  ansible.builtin.shell:
    cmd: sed -i "1s/.*/exit 0/" /opt/entrust/IOT_AGENT/Resources/ntpEPA.sh
  become: true

- name: Create entrust user
  ansible.builtin.shell:
    cmd: sed -i "1s/.*/exit 0/" /opt/entrust/IOT_AGENT/Process_restarter
  become: true

- name: create CA Certificates directory in /opt/entrust/cert/
  ansible.builtin.shell:
    cmd: mkdir -p /opt/entrust/IOT_AGENT/induslog/
  become: true

- name: Create entrust user
  ansible.builtin.shell:
    cmd: chmod -R 700 /opt/entrust
  become: true

- name: run IOT Agent configuration script on target machine with provided varia                                                                             bles
  ansible.builtin.shell:
    cmd: sh /opt/entrust/IOT_AGENT/runIoTAgent.sh 10.1.167.42 8030 ITA RSA-2048
    chdir: /tmp/IOT_AGENT/
  become: true
